
image: ghcr.io/ila-embsys/ada-project-example:master

tasks:
  - init: make init-repo

vscode:
  extensions:
    - marus25.cortex-debug
    - adacore.ada
    - llvm-vs-code-extensions.vscode-clangd
    - mhutchie.git-graph
    - vadimcn.vscode-lldb
    - ibm.output-colorizer
    - huntertran.auto-markdown-toc
    - cheshirekow.cmake-format
    - xaver.clang-format