
image:
  file: .gitpod.Dockerfile

tasks:
  - init: make init-repo

vscode:
  extensions:
    - marus25.cortex-debug
    - adacore.ada
    - llvm-vs-code-extensions.vscode-clangd
    - mhutchie.git-graph
    - vadimcn.vscode-lldb
    - ibm.output-colorizer
