manifest:
  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos

    - name: zephyr-ada
      url-base: https://github.com/zephyr-ada

    - name: thirdpin
      url-base: https://github.com/thirdpin

  # Please add items below based on alphabetical order
  projects:
    - name: cmsis
      remote: upstream
      revision: 542b2296e6d515b265e25c6b7208e8fea3014f90
      path: modules/hal/cmsis

    - name: hal_stm32
      remote: upstream
      revision: d1bc80d021f4ebc31f6e8b36f14b738cc26c7b03
      path: modules/hal/stm32

    - name: segger
      remote: upstream
      revision: 874d9e9696b00c09f9eeefe839028dc25fe44983
      path: modules/debug/segger

    - name: zephyr-ada-gnat-rts
      remote: zephyr-ada
      revision: b2593b5e84a46067784c3938091e72c7897b2556 
      path: modules/gnat

    - name: zephyr
      remote: zephyr-ada
      revision: v2.4-ada-branch
      path: zephyr
      west-commands: scripts/west-commands.yml

  self:
    path: app
